### ISSUE TITLE
`build-plugin-component-multiple`插件, 默认配置运行错误

### ISSUE THREAD

**Issue by fimars** [alibaba/lowcode-engine#1243]
## **Describe the bug (required)** / **详细描述 bug（必填）**

用脚手架生成的多物料组件库运行 `npm run build`会报错

---

## **Screenshots (optional)** / **bug 截图（可选）**
```bash
TypeError: Cannot read property 'replace' of undefined
ERR!     at sanitizeAddonName (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:117:41)
ERR!     at path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:240:31
ERR!     at Array.forEach (<anonymous>)
ERR!     at _callee$ (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:232:33)
ERR!     at tryCatch (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:64:40)
ERR!     at Generator.invoke (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:299:22)
ERR!     at Generator.next (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:124:21)
ERR!     at asyncGeneratorStep (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:68:103)
ERR!     at _next (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:70:194)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!  TypeError: Cannot read property 'replace' of undefined
ERR!     at sanitizeAddonName (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:117:41)
ERR!     at path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:240:31
ERR!     at Array.forEach (<anonymous>)
ERR!     at _callee$ (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:232:33)
ERR!     at tryCatch (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:64:40)
ERR!     at Generator.invoke (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:299:22)
ERR!     at Generator.next (path\lowcode-engine-materials\node_modules\@storybook\addon-docs\node_modules\regenerator-runtime\runtime.js:124:21)
ERR!     at asyncGeneratorStep (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:68:103)
ERR!     at _next (path\lowcode-engine-materials\node_modules\@storybook\telemetry\dist\cjs\storybook-metadata.js:70:194)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

---

## **Additional context (optional)** / **更多额外信息（可选）**

![image](https://user-images.githubusercontent.com/16299018/202656895-a6a2158e-7f98-43b1-90bc-ba0729cc0258.png)

Line: 128
```jsx
    multipleProps.addons || {}
```
这一行建议不要这样处理，build.json没有传入 addons 配置时就会报错。

![image](https://user-images.githubusercontent.com/16299018/202657093-f69341a2-2172-4033-9c9b-02b97b404765.png)

**Comment by eternalsky** [comment]
@mark-ck 大佬看看，目前组件库 build 确实有这个问题

**Comment by jinchanz** [comment]
新的组件库模板已经移除了对 build-plugin-component-multiple 的依赖，可以试试 `npm init @alilc/element@1.1.5-beta.0 react-comps-new --registry=https://registry.npmmirror.com`

**Comment by fimars** [comment]
thanks
