### ISSUE TITLE
「协议」增加 type: 'JSExpression' | 'JSFunction' 结构中 source 字段

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#1271]
source 字段可用于填充用户原始输入值，value 字段保存编译后的值，用于运行态。

比如：
![image](https://user-images.githubusercontent.com/1195765/203890342-07107cc6-c5b8-4da4-bf3b-bc767c2699e6.png)

此时 state?.x 在低版本浏览器下可能会直接 crash，假如保存为
```js
{
  type: 'JSExpression',
  value: 'state ? state.x : undefined', // 手写示意，勿cue
  source: 'state?.x'
}
```
则能很好的解决运行态，以及编辑态数据回填的问题，JSFunction 同理~

**Comment by yz1311** [comment]
这个还未实现吗?

**Comment by LeoYuan** [comment]
协议归协议，具体要使用方自己实现，比如 JS 面板、组件函数属性 等

**Comment by yz1311** [comment]
> 协议归协议，具体要使用方自己实现，比如 JS 面板、组件函数属性 等

请问，我这边准备将JSExpression里面的内容，在运行态，统一先转换成es5的代码，然后再执行，但是?.这种语法
```
this.state.prizeInfo?.url
```
会被编译成
```
var _this$state$prizeInfo;
    (_this$state$prizeInfo = this.state.prizeInfo) === null || _this$state$prizeInfo === void 0 ? void 0 : _this$state$prizeInfo.url;
```

然后这个东西，会报错
```
SyntaxError:Unexpected token 'var'
    at new Function (<anonymous>)
    at parseExpression (common.js:255:1)
    at PageRenderer.parseThisRequiredExpression [as __parseExpression] (common.js:263:1)
    at BaseRenderer._this.__parseProps (base.js:699:1)
    at base.js:772:1
    at common.js:322:1
    at Array.forEach (<anonymous>)
    at forEach (common.js:321:1)
    at BaseRenderer._this.__parseProps (base.js:767:1)
    at BaseRenderer._this.__getComponentProps (base.js:621:1)
    at BaseRenderer._this.__createVirtualDom (base.js:502:1)
    at base.js:605:1
    at Array.forEach (<anonymous>)
    at BaseRenderer._this.__getSchemaChildrenVirtualDom (base.js:604:1)
    at BaseRenderer._this.__createVirtualDom (base.js:547:1)
    at base.js:605:1
    at Array.forEach (<anonymous>)
    at BaseRenderer._this.__getSchemaChildrenVirtualDom (base.js:604:1)
    at BaseRenderer._this.__createVirtualDom (base.js:547:1)
    at base.js:605:1
    at Array.forEach (<anonymou
```

这个有办法解决吗?

**Comment by yz1311** [comment]
> `(() => { return ${code}; })()` ?

可以，谢谢![187B9C4D](https://github.com/alibaba/lowcode-engine/assets/9854019/8e5437a8-136e-497b-ab33-a70eb7fa03b6)，一个普通的页面转换时间大概100多ms，完全可以接受

给有需要的同学参考下:
```
  try {
    //判断一些常见的es6+写法是否支持
    eval(`
      []?.a;
      []??'';
      '123'.includes('1');
      '123'.startsWith('1');
      '123'.endsWith('1');
    `);
  } catch (e) {
    //将chidren组件中的JSExpression编译成es5的代码
    function getIds(lists) {
      if(Array.isArray(lists)) {
        if(lists.length === 0) {
          return;
        }
        lists.forEach(item=>{
          getIds(item)
        })
      } else {
        if(lists) {
          Object.keys(lists).forEach(key=>{
            //如果是对象，则递归
            if(lists[key] && typeof lists[key] === 'object') {
              //部分情况下不需要转换,减少遍历的时间
              if(['style'].indexOf(key)>=0 || lists[key].type === 'JSFunction') {
                return;
              }
              //判断是否是否需要转换  JSFunction因为只是简单绑定，不做转换
              if(lists[key].type === 'JSExpression') {
                //说明有需要转换的代码
                if(/\?\./.test(lists[key].value)
                  || /\.includes\(/.test(lists[key].value)
                  || /\.startsWith\(/.test(lists[key].value)
                  || /\.endsWith\(/.test(lists[key].value)) {
                  //编译成es5的代码
                  const transformResult = transformJS(`(() => { return ${lists[key].value} })()`, defaultBabelConfig);
                  lists[key].value =
                    transformResult.code?.
                    replace(/\r|\n/g,'')
                }
              } else {
                getIds(lists[key])
              }
            }
          })
        }
      }
    }
    getIds(pageJson.children);
  }
```
