### ISSUE TITLE
给按钮绑定事件用this.$(xxx)打开对话框报错

### ISSUE THREAD

**Issue by footya** [alibaba/lowcode-engine#1397]
## 想实现按钮绑定事件打开对话框，按照官方文档实例试了不生效

报错如下
```
react-dom.production.min.js:32 Uncaught TypeError: __self.$(...).open is not a function
    at e.onClick_new (eval at Yr (preview.js:1:71232), <anonymous>:6:30)
    at e.eval (eval at qr (preview.js:1:70905), <anonymous>:3:50)
    at r (button.tsx:148:59)
```
![image](https://user-images.githubusercontent.com/1920923/209088212-e7f29894-01ac-4c75-8cdb-eef811a725a0.png)

demo入口
https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html

schema如下：
```
{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {
    "ref": "outerView",
    "style": {
      "height": "100%"
    }
  },
  "fileName": "/",
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "info"
      }
    ]
  },
  "state": {
    "text": {
      "type": "JSExpression",
      "value": "\"outer\""
    },
    "isShowDialog": {
      "type": "JSExpression",
      "value": "false"
    }
  },
  "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
  "lifeCycles": {
    "componentDidMount": {
      "type": "JSFunction",
      "value": "function componentDidMount() {\n  console.log('did mount');\n}",
      "source": "function componentDidMount() {\n  console.log('did mount');\n}"
    },
    "componentWillUnmount": {
      "type": "JSFunction",
      "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}",
      "source": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
    }
  },
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n}",
      "source": "function testFunc() {\n  console.log('test func');\n}"
    },
    "onClick": {
      "type": "JSFunction",
      "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}",
      "source": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
    },
    "closeDialog": {
      "type": "JSFunction",
      "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}",
      "source": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
    },
    "onClick_new": {
      "type": "JSFunction",
      "value": "function onClick_new() {\n  this.$('modal-f8f4f046').open();\n}",
      "source": "function onClick_new() {\n  this.$('modal-f8f4f046').open();\n}"
    }
  },
  "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n\n\tonClick_new(){\n    this.$('modal-f8f4f046').open();\n\t}\n}",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "Button",
      "id": "node_oclbyr8vot8",
      "props": {
        "type": "primary",
        "children": "主按钮",
        "__component_name": "Button",
        "htmlType": "button",
        "size": "middle",
        "shape": "default",
        "icon": {
          "type": "JSSlot",
          "value": [
            {
              "componentName": "Icon",
              "id": "node_oclbyr8vota",
              "props": {
                "type": "SmileOutlined",
                "size": 20,
                "rotate": 0,
                "spin": false,
                "__component_name": "Icon"
              },
              "hidden": false,
              "title": "",
              "isLocked": false,
              "condition": true,
              "conditionGroup": ""
            }
          ]
        },
        "block": false,
        "danger": false,
        "ghost": false,
        "disabled": false,
        "ref": "button-e1ece0c9",
        "__events": {
          "eventDataList": [
            {
              "type": "componentEvent",
              "name": "onClick",
              "relatedEventName": "onClick_new"
            }
          ],
          "eventList": [
            {
              "name": "onClick",
              "template": "onClick(event,${extParams}){\n// 点击按钮时的回调\nconsole.log('onClick', event);}",
              "disabled": true
            }
          ]
        },
        "onClick": {
          "type": "JSFunction",
          "value": "function(){this.onClick_new.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
        }
      },
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    },
    {
      "componentName": "Modal",
      "id": "node_oclbyr8vot4",
      "props": {
        "title": "Basic Modal",
        "okText": "确认",
        "cancelText": "取消",
        "visible": false,
        "destroyOnClose": true,
        "__component_name": "Modal",
        "centered": false,
        "closable": true,
        "confirmLoading": false,
        "forceRender": true,
        "keyboard": true,
        "mask": true,
        "maskClosable": true,
        "bodyStyle": {},
        "maskStyle": {},
        "ref": "modal-f8f4f046"
      },
      "hidden": true,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    }
  ]
}
```

**Comment by liujuping** [comment]
每个系列的组件使用方式不一样，ant 的弹窗组件是通过绑定变量来实现弹窗的显示和隐藏

![image](https://user-images.githubusercontent.com/11935995/210049732-6185af6e-d6fc-4a58-8db0-b432e5184c77.png)

![image](https://user-images.githubusercontent.com/11935995/210049765-18ac523f-d160-4267-b4df-e7a89665b0d8.png)

schema 示例：

```
{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {
    "ref": "outerView",
    "style": {
      "height": "100%"
    }
  },
  "fileName": "/",
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "info"
      }
    ]
  },
  "state": {
    "text": {
      "type": "JSExpression",
      "value": "\"outer\""
    },
    "isShowDialog": {
      "type": "JSExpression",
      "value": "false"
    }
  },
  "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
  "lifeCycles": {
    "componentDidMount": {
      "type": "JSFunction",
      "value": "function componentDidMount() {\n  console.log('did mount');\n}",
      "source": "function componentDidMount() {\n  console.log('did mount');\n}"
    },
    "componentWillUnmount": {
      "type": "JSFunction",
      "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}",
      "source": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
    }
  },
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n}",
      "source": "function testFunc() {\n  console.log('test func');\n}"
    },
    "onClick": {
      "type": "JSFunction",
      "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}",
      "source": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
    },
    "closeDialog": {
      "type": "JSFunction",
      "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}",
      "source": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
    },
    "onClick_new": {
      "type": "JSFunction",
      "value": "function onClick_new() {\n  this.$('modal-f8f4f046').open();\n}",
      "source": "function onClick_new() {\n  this.$('modal-f8f4f046').open();\n}"
    }
  },
  "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n\n\tonClick_new(){\n    this.$('modal-f8f4f046').open();\n\t}\n}",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "Button",
      "id": "node_oclbyr8vot8",
      "props": {
        "type": "primary",
        "children": "主按钮",
        "__component_name": "Button",
        "htmlType": "button",
        "size": "middle",
        "shape": "default",
        "icon": {
          "type": "JSSlot",
          "value": [
            {
              "componentName": "Icon",
              "id": "node_oclbyr8vota",
              "props": {
                "type": "SmileOutlined",
                "size": 20,
                "rotate": 0,
                "spin": false,
                "__component_name": "Icon"
              },
              "hidden": false,
              "title": "",
              "isLocked": false,
              "condition": true,
              "conditionGroup": ""
            }
          ]
        },
        "block": false,
        "danger": false,
        "ghost": false,
        "disabled": false,
        "ref": "button-e1ece0c9",
        "__events": {
          "eventDataList": [
            {
              "type": "componentEvent",
              "name": "onClick",
              "relatedEventName": "onClick_new"
            }
          ],
          "eventList": [
            {
              "name": "onClick",
              "template": "onClick(event,${extParams}){\n// 点击按钮时的回调\nconsole.log('onClick', event);}",
              "disabled": true
            }
          ]
        },
        "onClick": {
          "type": "JSFunction",
          "value": "function(){this.onClick_new.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
        }
      },
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    },
    {
      "componentName": "Modal",
      "id": "node_oclbyr8vot4",
      "props": {
        "title": "Basic Modal",
        "okText": "确认",
        "cancelText": "取消",
        "visible": false,
        "destroyOnClose": true,
        "__component_name": "Modal",
        "centered": false,
        "closable": true,
        "confirmLoading": false,
        "forceRender": true,
        "keyboard": true,
        "mask": true,
        "maskClosable": true,
        "bodyStyle": {},
        "maskStyle": {},
        "ref": "modal-f8f4f046"
      },
      "hidden": true,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    }
  ]
}
```
