### ISSUE TITLE
@alifd/fusion-ui版本不存在以及页面引入报错问题

### ISSUE THREAD

**Issue by caoshaohua1025** [alibaba/lowcode-engine#143]
lowcode-demo在page里添加table之后，下载zip包，解压之后package.json配置出现"@alifd/fusion-ui": "1.0.24-21",npm上不存在的版本，设置为最新版之后，page中引入会报错，请问下是什么问题

**Comment by lijiaxu1996** [comment]
> lowcode-demo在page里添加table之后，下载zip包，解压之后package.json配置出现"@alifd/fusion-ui": "1.0.24-21",npm上不存在的版本，设置为最新版之后，page中引入会报错，请问下是什么问题

这个你得等官方修复呢，我之前也遇到了，包的问题，估计npm没更新呢

**Comment by zhaoliang233** [comment]
并且在导出的那个页面(src/pages/$/index.tsx)的引入路径也有问题
```code
import { ProDialog, ProForm, Filter } from "@alifd/fusion-ui/src/index.tsx";
import { ProTable } from "@alifd/fusion-ui/src/pro-table/index.tsx";
```
实际node_modules对应的包是没有这个路径的，改为
```code
import { ProDialog, ProForm, Filter } from "@alifd/fusion-ui";
import { ProTable } from "@alifd/fusion-ui;
```
后，项目启动时不会报错，但是在启动后，控制台会有报错信息
**ReferenceError: PropTypes is not defined**
对应的代码
![image](https://user-images.githubusercontent.com/40988703/158974464-5b0151d7-7320-4531-9935-f8c3bd31ffeb.png)

**Comment by lijiaxu1996** [comment]
提供一个办法，去npmjs.org上面直接搜索对应的报名，就会获取最新的版本的，但是有些包还是等官方发布吧~

**Comment by caoshaohua1025** [comment]
> 并且在导出的那个页面(src/pages/$/index.tsx)的引入路径也有问题
> 
> ```
> import { ProDialog, ProForm, Filter } from "@alifd/fusion-ui/src/index.tsx";
> import { ProTable } from "@alifd/fusion-ui/src/pro-table/index.tsx";
> ```
> 
> 实际node_modules对应的包是没有这个路径的，改为
> 
> ```
> import { ProDialog, ProForm, Filter } from "@alifd/fusion-ui";
> import { ProTable } from "@alifd/fusion-ui;
> ```
> 
> 后，项目启动时不会报错，但是在启动后，控制台会有报错信息 **ReferenceError: PropTypes is not defined** 对应的代码 ![image](https://user-images.githubusercontent.com/40988703/158974464-5b0151d7-7320-4531-9935-f8c3bd31ffeb.png)

请问这个报错你解决了吗，

**Comment by liujuping** [comment]
> 

参考：https://github.com/alibaba/lowcode-engine/issues/153

**Comment by gaorongfu** [comment]
这是一个层出不穷的bug，:-(
✖ Install fail! Error: [@alifd/fusion-ui@1.0.24-21] Can't find package @alifd/fusion-ui's version: 1.0.24-21
Error: [@alifd/fusion-ui@1.0.24-21] Can't find package @alifd/fusion-ui's version: 1.0.24-21
    at resolve (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:22:19)
    at async module.exports (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/index.js:21:10)
    at async _install (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:125:16)
    at async install (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:26:12)
    at async installOne (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:210:15)
    at async mapper (/home/gaorongfu/.nvm/versions/node/v16.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:149:5)

**Comment by mark-ck** [comment]
fixed in @alifd/fusion-ui@1.0.5
