### ISSUE TITLE
lowcode-engine/packages/engine build 报错

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1484]
## **Describe the bug (required)** / **详细描述 bug（必填）**
lowcode-engine/packages/engine 项目build 报错
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
提示检测到重复的插件
```bash
ERR! Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

不知道这个`plugin-proposal-class-properties`这个插件在哪配置的

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
拉取1.0.18版本 cd到packages/engine项目下 执行npm run build

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
```bash
ERR! Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "options": {
      "loose": true
    },
    "dirname": "/usr/local/zchi/lowcode-engine/packages/engine",
    "ownPass": false,
    "file": {
      "request": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
      "resolved": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "options": {
      "loose": true
    },
    "dirname": "/usr/local/zchi/lowcode-engine/packages/engine",
    "ownPass": false,
    "file": {
      "request": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
      "resolved": "/usr/local/zchi/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  }
] 
    at assertNoDuplicates (/usr/local/dtsz/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:182:13)
    at createDescriptors (/usr/local/dtsz/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:106:3)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/usr/local/dtsz/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:98:17)
    at createPluginDescriptors.next (<anonymous>)
    at /usr/local/dtsz/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:64:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/usr/local/dtsz/lowcode-engine/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/usr/local/dtsz/lowcode-engine/node_modules/gensync/index.js:251:28)
```
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.18] / 低代码引擎版本

**Comment by JackLian** [comment]
1.1版本已解决，还没正式发，可以用develop试试
然后正常来说你不需要自己build，引擎统一通过umd方式使用，不建议自行构建发布

**Comment by ChiZng** [comment]
@JackLian 看到develop上的[chore: add babel.config to fix build error](https://github.com/alibaba/lowcode-engine/commit/bc5ec038845e002884bc820b6cfe95f7420d35eb)的fix了。切到develop还是报这个错:fearful:。

我改了点源码，想发npm包在plugin中提示代码。

**Comment by lilithyang2018** [comment]
同样的错误
lowcode-plugins/packages/action-block 项目build 报错

![build-error](https://github.com/alibaba/lowcode-engine/assets/39897706/fb7b4222-fe52-4cc2-a3dd-ad7704539704)
依赖的lowcode-engine的版本是最新的1.1.7
