### ISSUE TITLE
低代码脚手架-调试机制, 控制台报错

### ISSUE THREAD

**Issue by zhb333** [alibaba/lowcode-engine#1492]
```sh
Uncaught (in promise) Error: [designer] Invariant failed: plugin dependency missing in 'EditorInitPlugin'
    at nf (invariant.ts:3:11)
    at e (plugin-manager.ts:164:5)
    at l (plugin-manager.ts:2:1)
    at Generator.<anonymous> (plugin-manager.ts:2:1)
    at Generator.next (plugin-manager.ts:2:1)
    at ah (plugin-manager.ts:2:1)
    at a (plugin-manager.ts:2:1)
    at plugin-manager.ts:2:1
    at new Promise (<anonymous>)
    at e.<anonymous> (plugin-manager.ts:2:1)
```

**Comment by Mrjing** [comment]
请问解决了吗，遇到同样的问题

**Comment by zhb333** [comment]
> 请问解决了吗，遇到同样的问题

本地调试，没有这个报错
