### ISSUE TITLE
digital envelope routines::unsupported

### ISSUE THREAD

**Issue by creasy2010** [alibaba/lowcode-engine#1506]
## Error
@alib/build-scripts 0.1.32
                                         10% buildingError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/dong/yzfworkbench/temp/lowcode-demo/demo-basic-antd/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

## **To Reproduce (required)** / **如何复现 bug？**

```sh
git clone git@github.com:alibaba/lowcode-demo.git
cd lowcode-demo
cd demo-general
npm install
npm run start
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
能正常启动

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Node v17 v18 v19 
 - Mac m1

**Comment by creasy2010** [comment]
把 Node.js 版本降为v16, 亲测有效.
