### ISSUE TITLE
lowcode-demo运行失败

### ISSUE THREAD

**Issue by zhangpengtwo** [alibaba/lowcode-engine#1675]
使用lowcode-demo运行demo。执行npm run start报错，是webpack版本高了吗？怎么解决
ERR! CONFIG Failed to load webpack config.
ERR! Cannot read properties of undefined (reading 'tap')
TypeError: Cannot read properties of undefined (reading 'tap')
    at HtmlWebpackPlugin.apply (/mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/html-webpack-plugin@5.5.0/node_modules/html-webpack-plugin/index.js:40:31)
    at webpack (/mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/webpack@4.46.0/node_modules/webpack/lib/webpack.js:51:13)
    at /mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/webpack@4.46.0/node_modules/webpack/lib/webpack.js:36:39
    at Array.map (<anonymous>)
    at webpack (/mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/webpack@4.46.0/node_modules/webpack/lib/webpack.js:36:24)
    at /mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/@alib+build-scripts@0.1.32/node_modules/@alib/build-scripts/lib/commands/start.js:70:24
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/d/wsl-ubuntu/lowcode-demo/demo-general/node_modules/.store/@alib+build-scripts@0.1.32/node_modules/@alib/build-scripts/lib/commands/start.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by JackLian** [comment]
最新的代码里已解决

**Comment by daifuyang** [comment]
实例中package.json中没有保存依赖 "html-webpack-plugin": "^4.5.2",实测直接装最新的就会报上面的错。指定安装4就好了cnpm i html-webpack-plugin@4 -D
