### ISSUE TITLE
Antd 高级组件demo添加`导航菜单`组件时报错

### ISSUE THREAD

**Issue by zemelLeong** [alibaba/lowcode-engine#1677]
## **Describe the bug (required)** / **详细描述 bug（必填）**

如题

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开这个页面 https://lowcode-engine.cn/demo/demo-basic-antd/index.html
2. 添加一个”导航菜单“组件

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/26835087/223013176-bbf7c4a5-4f32-4783-8eac-cdb9e095777d.png)

### 报错信息
```
TypeError: (e || []).map is not a function
    at i (useItems.tsx:19:10)
    at useItems.tsx:30:118
    at Array.map (<anonymous>)
    at i (useItems.tsx:19:10)
    at useItems.tsx:41:2
    at Object.useMemo (react-dom.production.min.js:216:441)
    at d.useMemo (react.production.min.js:32:231)
    at hd (useItems.tsx:48:12)
    at index.tsx:41:28
    at we (react-dom.production.min.js:84:293)
```

### debug 信息
![image](https://user-images.githubusercontent.com/26835087/223013384-2f6f80d3-3b33-47f5-a558-7c4d605e8dbc.png)

**Comment by JackLian** [comment]
@twinkle77 大佬辛苦看看

**Comment by dukanglyb** [comment]
什么时候能修复？
