### ISSUE TITLE
demo中需求占位组件拖拽尺寸大小时报错

### ISSUE THREAD

**Issue by unetcore** [alibaba/lowcode-engine#2390]
在官网的demo：https://lowcode-engine.cn/demo/demo-basic-fusion/index.html中直接放一个需求占位组件后，调整尺寸大小会报如下错误：

VM1424:23  Uncaught ReferenceError: logger is not defined
    at Object.eval [as onResize] (eval at bx (parse-func.ts:36:10), <anonymous>:23:9)
    at c.e (border-resizing.tsx:148:28)
    at c.e [as emit] (events.js:153:5)
    at e (event-bus.ts:83:27)
    at HTMLDocument.e (drag-resize-engine.ts:43:20)

本地运行demo也一样的问题。

**Comment by JackLian** [comment]
哪有占位组件？

**Comment by unetcore** [comment]
![1](https://github.com/alibaba/lowcode-engine/assets/17588730/ec7fea59-562b-4b89-b74c-2acd84e73161)
直接拖拽组件到设计窗口就可以看到了，本地调试了下，是try catch中的logger对象不存在
