### ISSUE TITLE
demo-workspace 无法运行

### ISSUE THREAD

**Issue by jlynet** [alibaba/lowcode-engine#2849]
plugin-manager.ts:122  Uncaught (in promise) Error: plugin resourceTabs skipped, engine check failed, current engine version is 1.3.0-beta, meta.engines.lowcodeEngine is ^1.3.0
    at e (plugin-manager.ts:122:13)
    at f (plugin-manager.ts:2:1)
    at Generator.<anonymous> (plugin-manager.ts:2:1)
    at Generator.next (plugin-manager.ts:2:1)
    at zp (plugin-manager.ts:2:1)
    at a (plugin-manager.ts:2:1)
    at plugin-manager.ts:2:1
    at new Promise (<anonymous>)
    at e.<anonymous> (plugin-manager.ts:2:1)
    at e.t (plugin-manager.ts:134:4)

**Comment by jlynet** [comment]
使用 以前下载的案例运行添加页面的时候提示错误：
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at e._normalizeXY (next.min.js:19:32020)
    at e._normalizePosition (next.min.js:19:31952)
    at e.setPosition (next.min.js:19:30630)
    at i.place (next.min.js:19:34795)
    at t.setPosition (next.min.js:11:187264)
    at t.componentDidMount (next.min.js:11:186462)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
