### ISSUE TITLE
报错信息：Error: the getUserInfo request should not fetch, please check the condition 以下是我dataSource的配置

### ISSUE THREAD

**Issue by yunnode** [alibaba/lowcode-engine#2856]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
麻烦帮看一下 下面这个问题：
报错信息：Error: the getUserInfo request should not fetch, please check the condition
以下是我dataSource的配置：
"dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "/mock/info.json"
        },
        "id": "info",
        "shouldFetch": {
          "type": "JSFunction",
          "value": "function() { \n  console.log('should fetch.....');\n  return true; \n}"
        }
      },
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 500000,
          "headers": {},
          "uri": "/aaa/bbb/getUser"
        },
        "id": "getUserInfo",
        "shouldFetch": {
          "type": "JSFunction",
          "value": "function updateUserInfo(res) { \n console.log('should fetch 2 ...'); \n console.log('getUserInfo res:', res); \nthis.setState({\n      stageData: res.data\n    });\n \nreturn res.data\n}"
        }
      }
    ]

 Error: the getUserInfo request should not fetch, please check the condition
    at RuntimeDataSourceItem.<anonymous> (src_apps_mobile_pages_create-special-customer_lowcode-page_tsx.chunk.js:4242:29)
    at step (main.bundle.js:108906:17)
    at Object.next (main.bundle.js:108855:14)
    at main.bundle.js:108829:67
    at new Promise (<anonymous>)
    at Module.__awaiter (main.bundle.js:108811:10)
    at RuntimeDataSourceItem.load (src_apps_mobile_pages_create-special-customer_lowcode-page_tsx.chunk.js:4195:20)
    at src_apps_mobile_pages_create-special-customer_lowcode-page_tsx.chunk.js:4390:60
    at step (main.bundle.js:108906:17)
    at Object.next (main.bundle.js:108855:14)

<img width="728" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/48727732/4c020aea-b8ea-47c3-9da7-69e736122da1">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
请规范一下提的标题以及内容。

**Comment by yunnode** [comment]
> 请规范一下提的标题以及内容。

好的

**Comment by yunnode** [comment]
> 请规范一下提的标题以及内容。

@eternalsky 您好，issue信息已调整，请帮看下问题，谢谢。

**Comment by YSMJ1994** [comment]
@yunnode 报错问题显示在 getUserInfo内 shouldFetch 表达式返回了非值，检查一下里面的表达式

**Comment by yunnode** [comment]
> shouldFetch
麻烦问下，你说的shouldFetch 表达式返回了「非值」，是指这个函数返回了非true的值的意思么？

        "shouldFetch": {
          "type": "JSFunction",
          "value": "function updateUserInfo(res) { \n console.log('should fetch 2 ...'); \n console.log('getUserInfo res:', res); \nthis.setState({\n      stageData: res.data\n    });\n \nreturn res.data\n}"
        }

**Comment by yunnode** [comment]
> @yunnode 报错问题显示在 getUserInfo内 shouldFetch 表达式返回了非值，检查一下里面的表达式
-----
麻烦问下，你说的shouldFetch 表达式返回了「非值」，是指这个函数返回了非true的值的意思么？

        "shouldFetch": {
          "type": "JSFunction",
          "value": "function updateUserInfo(res) { \n console.log('should fetch 2 ...'); \n console.log('getUserInfo res:', res); \nthis.setState({\n      stageData: res.data\n    });\n \nreturn res.data\n}"
        }

**Comment by yunnode** [comment]
> @yunnode 报错问题显示在 getUserInfo内 shouldFetch 表达式返回了非值，检查一下里面的表达式

你好，后来解决了，感谢。
