### ISSUE TITLE
页面编辑器( designer ) 里面的返回上一步 报错, Cannot read properties of null (reading 'componentMeta')

### ISSUE THREAD

**Issue by 946629031** [alibaba/lowcode-engine#417]
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

https://lowcode-engine.cn/demo/index.html
在线上Demo里 随便拖几个组件进来，然后点击 编辑器顶部的 返回上一步，并没有按照操作意愿返回了上一步操作，而是报错了

## 报错信息如下
```
history.ts:104 
TypeError: Cannot read properties of null (reading 'componentMeta')
    at R (modal-nodes-manager.ts:7:12)
    at e (modal-nodes-manager.ts:125:19)
    at new e (modal-nodes-manager.ts:34:10)
    at document-model.ts:372:32
    at X (control.ts:21:3)
    at e (document-model.ts:365:5)
    at Yt (mobx.esm.js:1255:15)
    at e.import (mobx.esm.js:1239:12)
    at e.redoer (document-model.ts:143:14)
    at e (history.ts:101:12)
```

**Comment by LeoYuan** [comment]
尝试拖了标题、对话框组件，无法复现，请再明确复现路径~

**Comment by 946629031** [comment]
你们说 无法复现的问题，我也发现了，感觉好像是偶发的。

然后，这个返回上一步，也只能返回一步呀，多点击几次发现，点击次数超过1次后，返回按钮 不再能返回。请问这个是BUG，还是原本就是这样设计的？
