### ISSUE TITLE
数据源面板导出错误

### ISSUE THREAD

**Issue by sunger** [alibaba/lowcode-engine#878]
地址：https://lowcode-engine.cn/demo/index.html
错误信息：

react_devtools_backend.js:3973 Error: schema should be object or boolean
    at m.P [as _addSchema] (index.js:69:111659)
    at m.v [as validate] (index.js:69:109463)
    at index.js:115:60370
    at Array.filter (<anonymous>)
    at n.deriveValue (index.js:115:60265)
    at new t (index.js:115:60916)
    at Yg (react-dom.production.min.js:68:243)
    at rh (react-dom.production.min.js:98:274)
    at zj (react-dom.production.min.js:228:490)
    at Th (react-dom.production.min.js:152:223)

**Comment by oneQiu** [comment]
同问，很早之前就有这个问题了，好像一直没修，我只能把导出按钮隐藏了

**Comment by meizilove258** [comment]
同等
