### ISSUE TITLE
lowcode-materials中的fusion-lowcode-materials包在构建时报错

### ISSUE THREAD

**Issue by winterlc** [alibaba/lowcode-engine#940]
## **lowcode-materials中的fusion-lowcode-materials包在构建时报错**
构建后运行正常，错误信息节选如下：
```
info WEBPACK         preview.html  538 KiB       0
info WEBPACK Compiled successfully
ERR! ENOENT: no such file or directory, open '/home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/dist/utils.js'
Error: ENOENT: no such file or directory, open '/home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/dist/utils.js'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at /home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/plugins/compatible.build.js:6:8
    at Context.<anonymous> (/home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/node_modules/@alib/build-scripts/lib/core/Context.js:267:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/node_modules/@alib/build-scripts/lib/core/Context.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/lowcode/lowcode-materials/packages/fusion-lowcode-materials/dist/utils.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alilc/lowcode-materials@1.0.3 lowcode:build: `build-scripts build --config ./build.lowcode.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @alilc/lowcode-materials@1.0.3 lowcode:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---

## **如何复现 bug？**
该问题仅在构建时出现

## **预期行为**
正常构建成功，不会报错

## **编译环境信息**
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
1、npm - 6.14.17
2、node - v14.19.3
3、ubuntu 20.04（WSL）

**Comment by hwyx** [comment]
请问这个问题有解决吗
